---
external_address: "{{ external_host_address }}"
external_interface: "{{ external_host_interface }}"
external_gateway: "{{ external_gateway_address }}"
internal_interface: "{{ internal_host_interface }}"
packages_libvirt_fedora:
  - libvirt
  - libvirt-client
  - python3-libvirt
  - python3-lxml
packages_openvswitch_fedora:
  - openvswitch
