---
- name: Setup systemd-networkd Configuration Files
  file:
    path: /etc/systemd/network
    state: directory
- name: Write Networkd OVS Bridge Configuration
  template:
    src: "{{ item }}.network"
    dest: "/etc/systemd/network/{{ item }}.network"
  with_items:
    - external
    - internal
    - ocp
- name: Write Networkd OVS mgmt Interface Configuration
  template:
    src: "{{ item }}.network"
    dest: "/etc/systemd/network/{{ item }}.network"
  with_items:
    - mgmt0
    - mgmt1
    - mgmt2
- name: Write Networkd OVS External Port Configuration
  template:
    src: "{{ item }}.network"
    dest: "/etc/systemd/network/{{ item }}.network"
  with_items:
    - "{{ external_interface }}"
- name: Disable Network Scripts and NetworkManager
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
    - network
    - NetworkManager
- name: Enable systemd-networkd & systemd-resolved
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - systemd-networkd
    - systemd-resolved
- name: Start systemd-resolved
  service:
    name: systemd-resolved
    state: started
- name: Symlink resolv.conf to systemd-resolved
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes

# name: Write Networkd Interface Configuration
# template:
#   src: interface.network
#   dest: "/etc/systemd/network/{{ item }}.network"
# when: "not '{{ item }}' == 'lo'"
# with_items: ansible_interfaces
